config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :restaurants , only: [:index, :show] do
      get "reviews", to: "restaurants#reviews", as: :reviews
      resources :dishes, only: [:index, :show]
      resources :bookings, only: [:index, :show, :new, :create, :update, :destroy]  do
        post 'pay', to: 'bookings#pay'
        get 'summary', to: 'bookings#summary'
        get 'checkin', to: 'bookings#checkin'
        resources :reviews, only: [:new, :show, :create, :destroy]
        resources :attendees, only: [:index, :new, :create, :destroy] do
          get 'accept', to: 'attendees#accept'
          resources :orders
        end
      end
  end

  resources :users, only: [:show, :edit] do
    get "reviews", to: "users#reviews", as: :reviews
    get "bookings", to: "users#bookings", as: :bookings
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  include PgSearch::Model
  pg_search_scope :search_by_first_name_and_last_name, against: [:first_name, :last_name, :email]

  mount_uploader :photo, PhotoUploader
  has_many :bookings, dependent: :destroy
  has_many :attendees, dependent: :destroy
  has_many :reviews, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_first_booking
  before_action :set_first_restaurant

  def show
    @user = current_user
    # Get the Attendee where User is Attendee, not yet accepted and Booking open (Add opento Booking model)
    @attendee_invitation = attendee_invitations_for_user(@user).last
  end

  def bookings
    @user = User.find(params[:user_id])
    @bookings = @user.bookings.sort_by(&:date).reverse
  end

  def reviews
    @user = User.find(params[:user_id])
    @reviews = Review.joins(:booking).where("bookings.user_id = #{@user.id}").order("bookings.date DESC")
  end

  def edit
    @user = current_user
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user.destroy
    redirect_to restaurants_path
  end

  private

  def users_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

app/views/users/bookings.html.erb
<%  @page_title = "My bookings" %>

<!-- Conditional formatting of the tab buttons -->
<% content_for(:tab_user_class, "tab_user_active") %>
<!-- end -->

<!-- Hide CheckedIn Button on Pages other than specific booking -->
<% content_for(:nav_checkedin_class, "nav_checkedin_invisible") %>
<!-- end -->



<% @bookings.each do |booking| %>
  <div class="card-box-shadow card-large">
    <div class="card-large-img">
      <%= cl_image_tag(booking.restaurant.photo,width: 400, height: 300, crop: :fill) %>
    </div>
    <div class="card-large-content-bookings flex-between vertical-center">
      <div>
        <h3><%= booking.restaurant.name %></h3>
        <p class="blue-font"><%= booking.date.strftime("%d/%m/%Y") %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/users/reviews.html.erb
<!-- Conditional formatting of the tab buttons -->
<% content_for(:tab_user_class, "tab_user_active") %>
<!-- end -->

<!-- Hide CheckedIn Button on Pages other than specific booking -->
<% content_for(:nav_checkedin_class, "nav_checkedin_invisible") %>
<!-- end -->

<%  @page_title = "My reviews" %>


  <% @reviews.each do |review| %>
  <% restaurant = review.booking.restaurant %>
    <div class="card-box-shadow card-large my-review">
      <div class="card-large-img">
        <%= cl_image_tag(restaurant.photo,width: 400, height: 300, crop: :fill) %>
      </div>
      <div class="review-whole">
        <div class="restaurant-name-card">
          <%= link_to restaurant_path(restaurant) do %>
            <h3><%= restaurant.name %></h3>
          <% end %>
          <div style="line-height: 18px; font-size: 15px;">
            <div class="my-review-content-stars">
              <div style="display:flex;">
                <% review.rating.times do %>
                  <i class="fas fa-star icon-stars"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <p><%= review.content.truncate(80) %></p>
        <small><%= review.booking.date.strftime("%d/%m/%Y") %></small>
      </div>
    </div>
  <% end %>

app/views/users/show.html.erb
<%  @page_title = "#{@user.first_name}'s Profile" %>
<!-- Conditional formatting of the tab buttons -->
<% content_for(:tab_user_class, "tab_user_active") %>
<!-- end -->
<!-- Hide CheckedIn Button on Pages other than specific booking -->
<% content_for(:nav_checkedin_class, "nav_checkedin_invisible") %>
<!-- end -->
<div>
  <div class="text-center" style="margin-bottom: 24px;">
    <%= cl_image_tag(current_user.photo, :class => "avatar-extra-large button-area") %>
  </div>
  <!-- Section to show Invitations -->
  <% if @attendee_invitation %>
    <h1>New invitation</h1>
    <div class="card-box-shadow card-large">
      <div class="card-large-img">
        <%= cl_image_tag(@attendee_invitation.booking.restaurant.photo,width: 400, height: 300, crop: :fill) %>
      </div>
      <div class="card-large-content">
        <p><strong> <%= @attendee_invitation.booking.user.first_name %></strong></p>
        <p><strong><%= @attendee_invitation.booking.restaurant.name %></p>
          <p class ="booktime"> <%= @attendee_invitation.booking.date.to_s(:invite_time) %></p>
          <strong></p>
        </div>
        <div class="button-area">
          <%= link_to restaurant_booking_attendee_accept_path(@attendee_invitation.booking.restaurant, @attendee_invitation.booking, @attendee_invitation) do %>
            <button class = "button-invitation button-short invitation-buton">Accept</button>
            <button class = "decbutton button-short invitation-buton">Decline</button>
          <% end %>
        </div>
      </div>
    <% else %>
      <p>No outsanding invitation</p>
    <% end %>
    <div class="card-small card-box-shadow button-area">
      <%= link_to edit_user_registration_path, class: "link" do %>
        <h3 class="user-card-title">Your details</h3>
      <% end %>
    </div>
    <div class="card-small card-box-shadow button-area">
      <%= link_to user_reviews_path(@user), class: "link" do %>
        <h3 class="user-card-title">Your reviews</h3>
      <% end %>
    </div>
    <div class="card-small card-box-shadow button-area">
      <%= link_to user_bookings_path(@user), class: "link" do %>
        <h3 class="user-card-title">Your bookings</h3>
      <% end %>
    </div>
    <div class="card-small card-box-shadow button-area">
      <%= link_to destroy_user_session_path, method: :delete, class: "link" do %>
        <h3 class="user-card-title">Log out</h3>
      <% end %>
    </div>
  </div>