config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :restaurants , only: [:index, :show] do
      get "reviews", to: "restaurants#reviews", as: :reviews
      resources :dishes, only: [:index, :show]
      resources :bookings, only: [:index, :show, :new, :create, :update, :destroy]  do
        post 'pay', to: 'bookings#pay'
        get 'summary', to: 'bookings#summary'
        get 'checkin', to: 'bookings#checkin'
        resources :reviews, only: [:new, :show, :create, :destroy]
        resources :attendees, only: [:index, :new, :create, :destroy] do
          get 'accept', to: 'attendees#accept'
          resources :orders
        end
      end
  end

  resources :users, only: [:show, :edit] do
    get "reviews", to: "users#reviews", as: :reviews
    get "bookings", to: "users#bookings", as: :bookings
  end
end

app/views/shared/_ad_dashboard.html.erb
<div class="container-dashboard container-insert">


	<div class="container-grid checkedin ">

		<h2>Checked-in [<%= @checkedin_bookings_hash.count %>]</h2>

		<% @checkedin_bookings_hash.each do |booking| %>

			<div class="container-bookings container-grid-item card-box-shadow checkedin_bookings"> 


			<% booking = Booking.where(id: booking, ordered:false, checkedin: true) %>
			<% booking = booking[0] %>

			<% time_now = (DateTime.now).utc %>
			<% checkin_time = booking.checkin_time%>
			<% elapsed_time = ((time_now - checkin_time ) / 1.minutes).to_i %>

				<div class="grid-item-flex">
					<div id="<%= booking.id %>" class="grid-item id-div checkedin-booking-id"> <b>Booking ID: </b><%= booking.id %></div>	
				 	<div class="grid-item"> <i class="order-button fas fa-plus-circle"></i></div>
				</div>

				<div class="grid-item"> <b>Lead: </b> <%= booking.user.first_name %> <%= booking.user.last_name %> </div>
				<div class="grid-item"> <b> Attendees: </b> <%= booking.attendees.count %></div>
				<div class="grid-item invisible"> N/A </div>


				<div class="grid-item-flex"> 
					
					<div class="grid-item"> 
						<b> Time since check-in: </b>
						<% if elapsed_time > 60 %>
							<em class="over-an-hour"><%= number_with_delimiter(elapsed_time, :delimiter => ',') %>  minutes </em> 
						<% else %>
							<em> <%= elapsed_time %> minutes</em> 
						<% end %> 
					</div>

					<div class="grid-item"> 
						<button class="button-status-checkedin checkedin">Checked in </button>	
					</div>

				</div>

			<div class="hide container-attendee"> 
				<h5>All attendees [<%= booking.attendees.count %>]:</h5>
				<% booking.attendees.each do |attendee| %>
					<div class="grid-item">  <%= attendee.user.first_name  %> <%= attendee.user.last_name  %></div>
				<% end %>
			</div>
		
		</div>

	<% end %>
	</div> 



	<div class="container-grid ordered">

		<h2>Ordered [<%= @open_orders.count %>]</h2> 

		<% @open_orders.each do |booking| %>


		<div class="container-bookings container-grid-item card-box-shadow ">

			<% booking = Booking.where(id: booking, ordered:true, checkedin: true) %>
			<% booking = booking[0] %>

			<% time_now = (DateTime.now).utc %>
			<% checkin_time = booking.checkin_time%>
			<% elapsed_time = ((time_now - checkin_time ) / 1.minutes).to_i %>


			<div class="grid-item-flex">
					<div id="<%= booking.id %>" class="grid-item id-div ordered-booking-id"> <b>Booking ID: </b><%= booking.id %></div>	
			 	<div class="grid-item"> <i class="order-button fas fa-plus-circle"></i></div>
			</div>


			<div class="grid-item"> 
				<b>Lead: </b> <%= booking.user.first_name %> <%= booking.user.last_name %>
			</div>

			<div class="grid-item-flex grid-item"> 
				<div> <b> Attendees: </b> <%= booking.attendees.count %></div>
				
				<% if booking.service_status == true %>
					<div> <b> Table served? </b>
					    <%= link_to ('<i class="fa fa-check-square box-check" aria-hidden="true"></i>').html_safe, admin_dashboard_update_service_status_path(booking: booking.id),
				            method: :patch,
				            data: {confirm: "Are you sure?"}  %> 
					</div>
				<% else %>
					<div> <b> Table served? </b>  
					    <%= link_to ('<i class="fa fa-square box-uncheck" aria-hidden="true"></i>').html_safe, admin_dashboard_update_service_status_path(booking: booking.id),
				            method: :patch,
				            data: {confirm: "Has this table been served?"}  %> 
					</div>

				<% end %>

			</div>

			<div class="grid-item"> 
				<b> Orders: </b> <%= booking.orders.count %>
			</div>

			<div class="grid-item-flex "> 
	
			<div class="grid-item"> 
				<b> Time since order: </b>
					<% if elapsed_time > 60 %>
						<em class="over-an-hour"><%= number_with_delimiter(elapsed_time, :delimiter => ',') %>  minutes </em> 
					<% else %>
						<em> <%= elapsed_time %> minutes</em> 
					<% end %> 
				</div>

				<div class="grid-item"> 
					<button class="button-status-checkedin ordered">Ordered</button>	
				</div>

			</div>

		<div id="container-table-order"> 

			<div class="hide container-attendee"> 

				<h5>Table order</h5>

				<% booking.attendees.each do |attendee| %>

					<div class="grid-sub-container"> 

						<% attendee = Attendee.find(attendee.id) %>
						<div class="grid-item grid-item-first">  <b>ID:</b> <%= attendee.id %></div>	
						<div class="grid-item"> <%= attendee.user.first_name %> <%= attendee.user.last_name %> </div>	
						<div class="grid-item"> <b>Orders: </b> <%= attendee.orders.count  %></div>
						<div class="grid-item"> <b> Bill: </b><%= humanized_money_with_symbol(attendee.orders.sum { |order| order.price }) %> </div>
						<div class="grid-item"> 
							<% if attendee.payment == true %>
								<div class="button-payment status-paid">PAID</div>
							<% else %>
								<div class="button-payment status-unpaid">UNPAID</div>
							<% end %>
						</div>

					</div>
					
					<% attendee.orders.each do |order| %>

						<div class="grid-sub-container">
							<div class="grid-item attendee-orders"> </div>
							<div class="grid-item attendee-orders"> <%= order.dish.name %> </div>
							<div class="grid-item attendee-orders"> </div>
							<div class="grid-item attendee-orders"> <%= humanized_money_with_symbol(order.dish.price) %></div>
							<div class="grid-item attendee-orders"> </div>
						</div>
					<% end %>

				<% end %>

			</div>

		</div> 

	</div>

	<% end %>
	</div>


	<div class="container-grid ordered">

		<h2>Closed [<%= @paid_bookings_hash.count  %>] </h2> 

		<% @paid_bookings_hash.each do |booking|  %>


		<div class="container-bookings container-grid-item card-box-shadow ">

			<% booking = Booking.find(booking[0]) %>


			<div class="grid-item-flex">
				<div id="<%= booking.id %>" class="grid-item id-div paid-booking-id"> <b>Booking ID: </b><%= booking.id %></div>	
			 	<div class="grid-item"> <i class="order-button fas fa-plus-circle"></i></div>
			</div>

			<div class="grid-item"> <b>Lead: </b> <%= booking.user.first_name %> <%= booking.user.last_name %> </div>
			<div class="grid-item"> <b> Attendees: </b> <%= booking.attendees.count %></div>
			<div class="grid-item"> <b> Orders: </b> <%= booking.orders.count %></div>

			<div class="grid-item-flex"> 
	
			<div class="grid-item"> <b> Paid at: </b> <%= booking.payment_time.strftime("%H:%M")  %> </div>

				<div class="grid-item"> 
					<button class="button-status-checkedin closed">Closed </button>	
				</div>

			</div>


		<div id="container-table-order"> 

			<div class="hide container-attendee"> 

				<h5>Table order</h5>

				<% booking.attendees.each do |attendee| %>

					<div class="grid-sub-container"> 

						<% attendee = Attendee.find(attendee.id) %>
						<div class="grid-item grid-item-first">  <b>ID:</b> <%= attendee.id %></div>	
						<div class="grid-item"> <%= attendee.user.first_name %> <%= attendee.user.last_name %> </div>	
						<div class="grid-item"> <b>Orders: </b> <%= attendee.orders.count  %></div>
						<div class="grid-item"> <b> Bill: </b><%= humanized_money_with_symbol(attendee.orders.sum { |order| order.price }) %> </div>
						<div class="grid-item"> 
							<% if attendee.payment == true %>
								<div class="button-payment status-paid">PAID</div>
							<% else %>
								<div class="button-payment status-unpaid">UNPAID</div>
							<% end %>
						</div>

					</div>
					
					<% attendee.orders.each do |order| %>

						<div class="grid-sub-container">
							<div class="grid-item attendee-orders"> </div>
							<div class="grid-item attendee-orders"> <%= order.dish.name %> </div>
							<div class="grid-item attendee-orders"> </div>
							<div class="grid-item attendee-orders"> <%= humanized_money_with_symbol(order.dish.price) %></div>
							<div class="grid-item attendee-orders"> </div>
						</div>
					<% end %>

				<% end %>

			</div>

		</div> 

	</div>

	<% end %>
	</div>


</div>
</div>

app/views/shared/_admin_dashboard.html.erb
<% render partial: 'shared/ad_dashboard' %>

app/views/shared/_checkedin.html.erb
<div class="checkedin-modal">
  <div class="card-box-shadow modal-box">
    <div>
      <h3>Check-in with your waiter</h3>
      <div class="qr-code">
        <%= image_tag("qrcode.jpg") %>
      </div>
      <div class="modal-buttons  flex-between">
        <div class="button-modal button-modal-cancel">
          Cancel
        </div>
        <% if @restaurant && @booking %>
          <%= link_to restaurant_booking_checkin_path(@restaurant, @booking) do %>
            <div class="button-modal button-modal-checkedin">
              Checked-in
            </div>
          <% end %>
        <% else %>
          <div class="button-modal button-modal-checkedin">
            Wrong Path !
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_ios.html.erb
<div class="navbar-ios">
  <div class="navbar-content">
    <div class="navbar-back same-space">
      <%= link_to request.referer.present? ? request.referer : root_path do %>
        <p class="<%= yield(:nav_chevron_class) %>">
          <i class="fas fa-chevron-left"></i>
        </p>
      <% end %>
    </div>
    <div class="navbar-title same-space">
      <% if current_page?('/') %>
        <p class="menyoo-title"><strong>Menyoo</strong></p>
      <% else %>
        <p><strong><%= @page_title %></strong></p>
      <% end %>
    </div>
    <div class="navbar-checkin same-space">
      <% if @booking %>
        <% if @booking.checkedin %>
          <p class="<%= yield(:nav_checkedin_class) %> checkedin-true"><i class="fas fa-toggle-on"></i></p>
        <% else %>
          <p class="<%= yield(:nav_checkedin_class) %> checkin-button"><i class="fas fa-toggle-off"></i></p>
        <% end %>
      <% else %>
        <p class="<%= yield(:nav_checkedin_class) %>"><i class="fas fa-toggle-off"></i></p>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_newbookingmodal.html.erb
<div class="booking-container checkedin-modal">


   <div class="new-booking">
      <div class="card-box-shadow modal-box-booking">


            <div class="container">
              <div class="form-wrapper button-area" style="margin: 0 auto;">
                <h2 class="create-booking-title">Select Date & Time</h2>

                <%= simple_form_for [@restaurant, @booking]  do |f| %>
                  <%= f.input :date, as: :string, required: false, label: false, input_html: {class: "datepicker"} %>
                  <%= f.button :submit, "Create Table", class: "button create-booking-button" %>
                <% end %>
              </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_newreviewmodal.html.erb
<div class="checkedin-modal">
  <div class="card-box-shadow modal-box-review">
    <div class="new-review">
      <%= simple_form_for([@restaurant, @booking, @review], remote: true) do |f| %>
        <h1>How was your experience?</h1>
        <br>
        <%= f.input :content %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", wrapper_html: {class: "new-review-rating"}%>
        <%= f.submit "Submit", class: "button button-medium", id: "form-submit" do%>
        <% end %>
      <% end %>
    </div>
    <div class="d-none" id="payment">
      <div class="new-review">
        <h1>Thank you for your feedback!</h1>
        <br>
        <p style="margin-top: 24px;">Your total bill amount</p>
        <p style="margin-top: 16px;"><strong><%= humanized_money_with_symbol(@amount_disp) %></strong></p>
        <!-- <p>Please click on the link below to proceed with payment</p> -->
        <button class="button button-medium" id="pay" style="margin-top: 50px;">PAY</button>
      </div>
    </div>
  </div>
</div>
<!-- JS -->
<script src="https://js.stripe.com/v3/"></script>
<script>
  const payment = document.getElementById('payment');
  const formSubmit = document.querySelector("#form-submit");
  <% if @order_left_to_pay > 0 %>
    formSubmit.addEventListener("click", () => {
      document.querySelector("form").classList.add("d-none");
      payment.classList.remove("d-none");
    })
  
    const paymentButton = document.getElementById('pay');
    paymentButton.addEventListener('click', () => {
      const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
          stripe.redirectToCheckout({
          sessionId: '<%= @payment.checkout_session_id %>'
        });
      });
  <% end %>
</script>

app/views/shared/_tabbar_ios.html.erb
<div class="tabbar-ios">
  <div class="tabbar-content">
    <!-- Home Tab -->
    <div class="navbar-back">
      <%= link_to root_path do %>
        <p class="<%= yield(:tab_home_class) %>"><i class="fas fa-home"></i></p>
      <% end %>
    </div>
    <!-- Your Table Tab -->
    <div class="navbar-title">
      <% if user_signed_in? %>
        <% if bookings_open_for_user(current_user).count != 0 %>
          <!--           <% @booking = bookings_open_for_user(current_user).last %>
          <% @restaurant = @booking.restaurant %> -->
          <%=  link_to restaurant_booking_path(@restaurant_first, @booking_first) do %>
            <p class="<%= yield(:tab_table_class) %>"><i class="fas fa-utensils"></i></p>
          <% end %>
        <% else %>
          <p class = "tab-unavailable"><i class="fas fa-utensils"></i></p>
        <% end %>
      <% else %>
        <p class = "tab-unavailable"><i class="fas fa-utensils"></i></p>
      <% end %>
    </div>
    <!-- User Profile Tab -->
    <div class="navbar-title">
      <% if user_signed_in? %>
        <%=  link_to user_path(current_user) do %>
          <div class="navbar-checkin">
            <p class="<%= yield(:tab_user_class) %>"><i class="fas fa-user"></i></p>
          </div>
        <% end %>
      <% else %>
        <%=  link_to new_user_session_path do %>
          <div class="navbar-checkin">
            <p class="tab-unavailable"><i class="fas fa-user-times"></i></p>
          </div>
        <% end %>
      <% end %>
      <% if attendee_invitations_for_user(current_user).count != 0 %>
        <%= image_tag("color-orange.png", :class => "red-notification") %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/menu_card.html.erb
<%= @test  %>

app/views/shared/review_summary.html.erb
TESING