config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount StripeEvent::Engine, at: '/stripe-webhooks'

  resources :restaurants , only: [:index, :show] do
      get "reviews", to: "restaurants#reviews", as: :reviews
      resources :dishes, only: [:index, :show]
      resources :bookings, only: [:index, :show, :new, :create, :update, :destroy]  do
        post 'pay', to: 'bookings#pay'
        get 'summary', to: 'bookings#summary'
        get 'checkin', to: 'bookings#checkin'
        resources :reviews, only: [:new, :show, :create, :destroy]
        resources :attendees, only: [:index, :new, :create, :destroy] do
          get 'accept', to: 'attendees#accept'
          resources :orders
        end
      end
  end

  resources :users, only: [:show, :edit] do
    get "reviews", to: "users#reviews", as: :reviews
    get "bookings", to: "users#bookings", as: :bookings
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  geocoded_by :address
    after_validation :geocode, if: :will_save_change_to_address?


  has_many :dishes, dependent: :destroy
  has_many :bookings
  has_many :reviews, through: :bookings, dependent: :destroy
  has_many :admin_users
  has_many :attendees, through: :bookings

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true

  mount_uploader :photo, PhotoUploader

  include PgSearch::Model

  pg_search_scope :search_by_restaurant,
    against: [:name, :address, :category],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def avarage_rating
    return 0 if reviews.empty?

    ratings = reviews.map(&:rating).compact
    (ratings.sum / ratings.size.to_f).round(1)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_first_booking
  before_action :set_first_restaurant

  def index
    if params[:query].present?
      @restaurants = Restaurant.search_by_restaurant(params[:query]).geocoded
      @restaurants_all = Restaurant.geocoded
    else
      @restaurants = Restaurant.geocoded
      @restaurants_all = Restaurant.geocoded
    end

    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant }),
        image_url: helpers.asset_url('menyoo-marker.png')
      }
    end

  end

  def show
    @restaurant = Restaurant.find(params[:id])

    if params[:query].present?
      @dishes_for_restaurant = @restaurant.dishes.search_by_dish(params[:query]).order(:name)
    else
      @dishes_for_restaurant = @restaurant.dishes.order(:name)
    end
    @categories = @dishes_for_restaurant.map(&:category).uniq.sort
    if @categories.include?("Desserts")
      @categories.delete("Desserts")
      @categories.push("Desserts")
    end


    if user_signed_in?
      if any_booking_open_for_user_restaurant?(current_user, @restaurant)
        @booking = bookings_open_for_user_restaurant(current_user, @restaurant).last
      else
        @booking = Booking.new
      end
      @attendee = Attendee.where(user: current_user, booking: @booking).last
      @order = Order.new
    end
  end

  def reviews
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reviews = Review.joins(:booking).where("restaurant_id = #{@restaurant.id}").order("bookings.date DESC")
  end


  private

  # def set_first_booking
  #   if user_signed_in?
  #     if bookings_open_for_user(current_user).count !=0
  #       @bookings_open = bookings_open_for_user(current_user).sort_by &:date
  #       @booking_first = @bookings_open[0]
  #     end
  #     return nil
  #   end
  #   return nil
  # end

  # def set_first_restaurant
  #   if user_signed_in?
  #     if bookings_open_for_user(current_user).count !=0
  #       @bookings_open = bookings_open_for_user(current_user).sort_by &:date
  #       @booking_first = @bookings_open[0]
  #       @restaurant_first = @booking_first.restaurant
  #     end
  #     return nil
  #   end
  #   return nil
  # end
end

app/views/restaurants/_info_window.html.erb
<%= link_to restaurant_path(restaurant), {class: "info-window"} do %>
  <h2><%= restaurant.name %></h2>
  <p><%= restaurant.category %></p>
<% end %>

app/views/restaurants/index.html.erb
<%  @page_title = "Welcome to Menyoo" %>
<!-- Conditional formatting of the tab buttons -->
<% content_for(:tab_home_class, "tab_home_active") %>
<!-- end -->
<!-- Hide back chevron on home page -->
<% content_for(:nav_chevron_class, "nav_chevron_invisible") %>
<!-- end -->
<!-- Hide CheckedIn Button on Pages other than specific booking -->
<% content_for(:nav_checkedin_class, "nav_checkedin_invisible") %>
<!-- end -->
<div class="search-section">
  <%= form_tag restaurants_path, method: :get do %>
    <div class="search-form-control button-area">
      <div>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "What are you in the mood for ?"
        %>
        <i id="delete-button", class="fas fa-times-circle"></i>
      </div>
      <%= submit_tag "Search", class: "button button-medium" %>
    </div>
  <% end %>
</div>
<div class="home-featured-section">
  <div class="home-header flex-between">
    <h1>Featured</h1>
    <div class="map-button">
      <i class="far fa-map"></i>  Search near me
    </div>
  </div>
  <% @restaurants.each do |restaurant| %>
    <div class="card-box-shadow card-large">
      <div class="card-large-img">
        <%= cl_image_tag(restaurant.photo,width: 400, height: 300, crop: :fill) %>
      </div>
      <div class="card-large-content">
        <div class="restaurant-name-card">
          <%= link_to restaurant_path(restaurant) do %>
            <h3><%= restaurant.name %></h3>
          <% end %>
          <div class="rating-stars">
            <% if restaurant.avarage_rating.zero? %>
              <p class="ratings-stars accent-font">No reviews</p>
            <% else %>
              <%= link_to restaurant_reviews_path(restaurant) do %>
                <div class="ratings-text">
                  <% restaurant.avarage_rating.round.times do %>
                    <i class="rating-stars fas fa-star"></i>
                  <% end %>
                  (<%= restaurant.reviews.size %>)
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
        <p class="grey-font"><%= restaurant.address %></p>
        <p>Category: <%= restaurant.category %></p>
      </div>
    </div>
  <% end %>
</div>
<div class="home-map-section hide">
  <div class="home-header flex-between">
    <h1>Map</h1>
    <div class="map-button">
      <i class="fas fa-list-ul"></i>
      See Featured
    </div>
  </div>
  <div class="card-box-shadow map-section">
    <div id="map"
      class="test-ana"
      style="width: 400px;
      height: 300px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
  <% @restaurants.each do |restaurant| %>
    <div id="mapshow">
      <%= link_to restaurant_path(restaurant) do %>
        <h3><strong><%= restaurant.name %></strong></h3>
        <p><%= restaurant.address %></p>
        <p><%= restaurant.category %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/restaurants/reviews.html.erb
<!-- Conditional formatting of the tab buttons -->
<% content_for(:tab_user_class, "tab_user_active") %>
<!-- end -->
<!-- Hide CheckedIn Button on Pages other than specific booking -->
<% content_for(:nav_checkedin_class, "nav_checkedin_invisible") %>
<!-- end -->
<%  @page_title = @restaurant.name %>
<h1>Reviews</h1>
<% @reviews.each do |review| %>
  <div class= "review-card">
    <div class=review-avatar>
      <%= cl_image_tag review.user.photo, class: "avatar" %>
      <div>
        <small><%= review.user.first_name %></small>
      </div>
    </div>
    <div class="review-whole">
      <div class="restaurant-name-card">
        <strong><%= review.title %></strong>
        <div style="line-height: 18px; font-size: 15px;">
          <div class="review-content-stars">
            <div style="display:flex;">
              <% review.rating.times do %>
                <i class="fas fa-star icon-stars"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <p><%= review.content %></p>
      <small><%= review.booking.date.strftime("%d/%m/%Y") %></small>
    </div>
  </div>
<% end %>

app/views/restaurants/show.html.erb
<%  @page_title = "Restaurant Page" %>
<!-- Conditional formatting of the tab buttons -->
<% if user_signed_in? %>
  <% if any_booking_open_for_user_restaurant?(current_user, @restaurant) %>
    <% content_for(:tab_table_class, "tab_table_active") %>
  <% else %>
    <% content_for(:tab_home_class, "tab_home_active") %>
  <% end %>
<% else %>
  <% content_for(:tab_home_class, "tab_home_active") %>
<% end %>
<!-- end -->
<!-- Hide CheckedIn Button on Pages other than specific booking -->
<% content_for(:nav_checkedin_class, "nav_checkedin_invisible") %>
<!-- end -->
<div class="restaurant-header ">
  <h1 id="rname"><%= @restaurant.name %></h1>
  <p id="raddress"><%= @restaurant.address %></p>
  <div class="rating-stars">
    <% if @restaurant.avarage_rating.zero? %>
      <p class="ratings-stars accent-font">No reviews</p>
    <% else %>
      <%= link_to restaurant_reviews_path(@restaurant) do %>
        <div class="ratings-text">
          <% @restaurant.avarage_rating.round.times do %>
            <i class="rating-stars fas fa-star"></i>
          <% end %>
          (<%= @restaurant.reviews.size %>)
        </div>
      <% end %>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <% if !any_booking_open_for_user_restaurant?(current_user, @restaurant) %>
      <div class="button-area">
        <button id="button-create-table" class = "button button-long">Create a Table</button>
      </div>
      <!-- Partial for the Create Table Modal -->
      <div class="newbooking-popup hide">
        <%= render 'shared/newbookingmodal' %>
      </div>
      <!-- end -->
    <% end %>
  <% else %>
  <% end %>
</div>
<div class="search-section">
  <%= form_tag restaurant_path(@restaurant), method: :get do %>
    <div class="search-form-control button-area search-area">
      <%= text_field_tag :query,

        params[:query],
        class: "form-control",
        placeholder: "Healthy or decadent ?"
        %>
      <i id="delete-button-two", class="fas fa-times-circle"></i>
      <%= submit_tag "Search", class: "button button-medium" %>
    </div>
  <% end %>
</div>
<h1>Menu</h1>
<% @categories.each do |category|  %>
  <h2><%= category %></h2>
  <% @dishes = @dishes_for_restaurant.select {|dish| dish.category == category }  %>
  <% @dishes.each do |dish|  %>
    <div class="card-box-shadow card-large">
      <div class="card-large-img">
        <%= cl_image_tag(dish.photo,width: 400, height: 300, crop: :fill) %>
      </div>
      <div class="card-large-content">
        <h3><%= dish.name %></h3>
        <p> <%= dish.description %></p>
        <div class="flex-between dish-info">
          <div class="timeprice">
            <p><%= humanized_money_with_symbol(dish.price)%></p>
            <p><i class="far fa-clock "></i> <%= dish.prep_time %></p>
          </div>
          <% if user_signed_in? %>
            <% if any_booking_open_for_user_restaurant?(current_user, @restaurant) && !@booking.attendees.all? {|attendee| attendee.payment == true }%>
              <div class = "hide" id= <%= "order-done-dish-#{dish.id}" %> >
                <button class="button-action button-color-grey"><i class="fas fa-check"></i></button>
              </div>


              <div class = "show" id=<%= "order-form-dish-#{dish.id}" %> >

                <% if @booking.checkedin == true %>
                  <%= simple_form_for [@restaurant, @booking, @attendee, @order], html:{class: "button_height"}, remote: true do |f| %>
                    <%= f.input :dish_id , as: :hidden, input_html: { value: dish.id } %>
                    <%= f.input :price , as: :hidden, input_html: { value: dish.price } %>
                    <%= f.submit "Order", class: "btn button-action button-color-blue id-of-dish-#{dish.id}" %>
                  <% end %>
                <% else %>
                <%= simple_form_for [@restaurant, @booking, @attendee, @order], html:{class: "button_height"}, remote: true do |f| %>
                    <%= f.input :dish_id , as: :hidden, input_html: { value: dish.id } %>
                    <%= f.input :price , as: :hidden, input_html: { value: dish.price } %>
                    <%= f.submit "Pre-order", class: "btn button-action pre-order button-color-blue id-of-dish-#{dish.id}" %>
                  <% end %>

                <% end %>

              </div>

            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>